[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/:func"
  to = "/.netlify/functions/:func"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/verify"
  to = "/verify.html"
  status = 200

[[redirects]]
  from = "/induction"
  to = "/induction.html"
  status = 200
